"""Production hardening batch

Revision ID: 6a9206cd7b66
Revises: b51c07904421
Create Date: 2026-05-26 12:34:53.392033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9206cd7b66'
down_revision = 'b51c07904421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_members_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('renewal_days', sa.Integer(), nullable=False, server_default='30')
        )

    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.create_index('ix_renewals_gym_prev_end', ['gym_id', 'previous_end'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.drop_index('ix_renewals_gym_prev_end')

    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.drop_column('renewal_days')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
