"""Add mobile_refresh_tokens table

Revision ID: 8623a65211ec
Revises: a3c4d5e6f7a8
Create Date: 2026-08-23 23:54:25.063709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8623a65211ec'
down_revision = 'a3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mobile_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobile_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_refresh_tokens_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_mobile_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('mobile_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_mobile_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_mobile_refresh_tokens_gym_id'))
        batch_op.drop_index(batch_op.f('ix_mobile_refresh_tokens_family_id'))

    op.drop_table('mobile_refresh_tokens')
    # ### end Alembic commands ###
