"""Initial schema

Revision ID: b51c07904421
Revises: 
Create Date: 2026-05-26 11:20:25.994217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51c07904421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gyms_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_gyms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gyms_subscription_status'), ['subscription_status'], unique=False)

    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'name', name='uq_plan_gym_name')
    )
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plans_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_plan_gym_active', ['gym_id', 'is_active'], unique=False)

    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_templates_gym_trigger', ['gym_id', 'trigger', 'is_active'], unique=False)

    op.create_table('qr_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_label', sa.String(length=160), nullable=True),
    sa.Column('upi_id', sa.String(length=160), nullable=True),
    sa.Column('qr_image_path', sa.String(length=512), nullable=True),
    sa.Column('qr_public_url', sa.String(length=512), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', name='uq_qr_settings_gym')
    )
    with op.batch_alter_table('qr_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_settings_gym_id'), ['gym_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_gym_created', ['gym_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_gym_id'), ['gym_id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('membership_start', sa.Date(), nullable=False),
    sa.Column('membership_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('ix_members_gym_expiry', ['gym_id', 'membership_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_members_gym_phone', ['gym_id', 'phone'], unique=False)
        batch_op.create_index('ix_members_gym_status', ['gym_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_status'), ['status'], unique=False)

    op.create_table('payment_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_verifications_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_verifications_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_verifications_status'), ['status'], unique=False)
        batch_op.create_index('ix_payments_gym_member', ['gym_id', 'member_id'], unique=False)
        batch_op.create_index('ix_payments_gym_status', ['gym_id', 'status'], unique=False)

    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('reminder_stage', sa.String(length=64), nullable=False),
    sa.Column('cycle_end_date', sa.Date(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('phone_snapshot', sa.String(length=40), nullable=False),
    sa.Column('message_snapshot', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'member_id', 'cycle_end_date', 'reminder_stage', 'channel', name='uq_reminder_member_cycle_stage_channel')
    )
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_logs_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_logs_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_reminders_gym_scheduled', ['gym_id', 'scheduled_for'], unique=False)
        batch_op.create_index('ix_reminders_gym_status', ['gym_id', 'status'], unique=False)

    op.create_table('renewal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('payment_verification_id', sa.Integer(), nullable=True),
    sa.Column('renewed_by_id', sa.Integer(), nullable=True),
    sa.Column('previous_end', sa.Date(), nullable=False),
    sa.Column('new_start', sa.Date(), nullable=False),
    sa.Column('new_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_verification_id'], ['payment_verifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['renewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewal_history_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_renewal_history_member_id'), ['member_id'], unique=False)
        batch_op.create_index('ix_renewals_gym_member', ['gym_id', 'member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewal_history', schema=None) as batch_op:
        batch_op.drop_index('ix_renewals_gym_member')
        batch_op.drop_index(batch_op.f('ix_renewal_history_member_id'))
        batch_op.drop_index(batch_op.f('ix_renewal_history_gym_id'))

    op.drop_table('renewal_history')
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_gym_status')
        batch_op.drop_index('ix_reminders_gym_scheduled')
        batch_op.drop_index(batch_op.f('ix_reminder_logs_status'))
        batch_op.drop_index(batch_op.f('ix_reminder_logs_member_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_logs_gym_id'))

    op.drop_table('reminder_logs')
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_gym_status')
        batch_op.drop_index('ix_payments_gym_member')
        batch_op.drop_index(batch_op.f('ix_payment_verifications_status'))
        batch_op.drop_index(batch_op.f('ix_payment_verifications_member_id'))
        batch_op.drop_index(batch_op.f('ix_payment_verifications_gym_id'))

    op.drop_table('payment_verifications')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_status'))
        batch_op.drop_index('ix_members_gym_status')
        batch_op.drop_index('ix_members_gym_phone')
        batch_op.drop_index(batch_op.f('ix_members_gym_id'))
        batch_op.drop_index('ix_members_gym_expiry')

    op.drop_table('members')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_gym_id'))
        batch_op.drop_index('ix_audit_gym_created')
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_gym_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('qr_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_settings_gym_id'))

    op.drop_table('qr_settings')
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_templates_gym_trigger')
        batch_op.drop_index(batch_op.f('ix_notification_templates_gym_id'))

    op.drop_table('notification_templates')
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_gym_active')
        batch_op.drop_index(batch_op.f('ix_membership_plans_gym_id'))

    op.drop_table('membership_plans')
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gyms_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_gyms_status'))
        batch_op.drop_index(batch_op.f('ix_gyms_slug'))

    op.drop_table('gyms')
    # ### end Alembic commands ###
